"""Object storage port for direct uploads. Business modules do not import a vendor SDK."""

from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True)
class ObjectStat:
    size: int
    mime_type: str


@dataclass(frozen=True)
class StoredObject:
    key: str
    url: str
    size: int


@dataclass(frozen=True)
class UploadGrant:
    token: str
    upload_url: str
    domain: str
    expires_in: int


class StorageProvider(Protocol):
    def generate_upload_token(
        self,
        *,
        key: str,
        content_type: str,
        size: int,
    ) -> UploadGrant:
        """Sign one insert-only upload. The token must not be logged."""

    def upload_bytes(self, *, key: str, content: bytes, content_type: str) -> StoredObject:
        """Store bytes generated by this process."""

    def upload_path(self, *, key: str, path: str, content_type: str) -> StoredObject:
        """Store a local file generated by this process."""

    def stat(self, key: str) -> ObjectStat | None:
        """Return the stored object, or None when it is absent."""

    def delete(self, key: str) -> None:
        """Remove the object. Missing objects are already gone."""

    def public_url(self, key: str) -> str:
        """Return the browser URL for a key this service created."""
